permalink: /:categories/:title/
title: 0xRick
email: 
description: Infosec Blog , CTF and Hack The Box write-ups , articles and other stuff
baseurl: "/" 
url: "https://0xrick.github.io" # the base hostname & protocol for your site, e.g. http://example.com

social_links:
  - url: https://twitter.com/Ahm3d_H3sham/
    icon: twitter-square
    color: cyan
  - url: https://facebook.com/Ahm3d.H3sham/
    icon: facebook-square
    color: blue
  - url: https://github.com/0xRick
    icon: github-square
    color: purple

# Build settings
markdown: kramdown
theme: jekyll-dash
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging
paginate: 4
paginate_path: "page:num"
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
